language: python
sudo: required

branches:
  only:
    - master

services:
  - docker

env:
  global:
    - CIBW_SKIP="cp26-* cp32-* cp33-*"
    - CIBW_BEFORE_BUILD="{pip} install six"
    - CIBW_TEST_COMMAND="python {project}/util/bee.py test -v"
# set user:pass for twine in travis CI setup for project

os:
  - linux

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.3"
  allow_failures:
    - os: osx

before_install:
  - sudo apt-get update -qq
  
install:
  - pip install six
  - pip install cython numpy scipy --use-wheel
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.3" ]] ; then
      pip install coverage coveralls --use-wheel
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]] ; then
      pip install cibuildwheel==0.5.1 twine --use-wheel
    fi

script:
  - make compile
  - echo $TRAVIS_PYTHON_VERSION
  - |
    if [[ "$TRAVIS_PYTHON_VERSION == "3.5" ]] ; then
      coverage run --source=fastmat util/bee.py test -v
      coverage run -a --source=fastmat util/bee.py list makedump
      coverage run -a --source=fastmat util/bee.py documentation -s Matrix algs.OMPinspect maxIter=0.0001 maxInit=0.01
      coverage run -a --source=fastmat util/bee.py calibrate Matrix
    elif [[ "$TRAVIS_PYTHON_VERSION == "3.6" ]] ; then
      cibuildwheel --output-dir wheelhouse
      ls -l wheelhouse/*
    fi

after_success: >
  if [[ "$TRAVIS_PYTHON_VERSION == "3.6" ]] ; then
    coveralls
    ls -l wheelhouse/*
    twine upload wheelhouse/*.whl
  fi
