language: python
sudo: required

branches:
  only:
    - master

services:
  - docker

python:
  - "2.7"
  - "3.6"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

before_install:
  - sudo apt-get update -qq
  
install:
  - pip install cython
  - pip install coverage coveralls # for CI
  - pip install cibuildwheel==0.5.1

script:
  - make compile
  - coverage run --source=fastmat util/bee.py test -v
  - cibuildwheel --output-dir wheelhouse

after_success: >
  if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
    coveralls
  fi
