language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "nightly"
    - os: linux
    - os: osx
  allow_failures:
    - python: "nightly"

install:
  - pip install coverage coveralls # for CI

script:
  - make compile
  - coverage run --source=fastmat util/bee.py test -v
  - pip install cibuildwheel==0.5.1
  - cibuildwheel --output-dir wheelhouse

after_success: >
  if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
    coveralls
  fi
