language: python

matrix:
  include:
    # Linux Python 2.7
    - sudo: required
      python: "2.7"
      services:
        - docker
    
    # Linux Python 3.6
    - sudo: required
      python: "3.6"
      services:
        - docker

install:
  - pip install cython
  - pip install coverage coveralls # for CI

script:
  - make compile
  - coverage run --source=fastmat util/bee.py test -v
  - pip install cibuildwheel==0.5.1
  - cibuildwheel --output-dir wheelhouse

after_success: >
  if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
    coveralls
  fi
