language: python

matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "nightly"
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
    - python: "nightly"

install:
  - pip install cython numpy scipy
  - pip install coverage coveralls # for CI

script:
  - make compile
  - coverage run --source=fastmat util/bee.py test -v

after_success: >
  if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
    coveralls
  fi
