environment:
  global:
    CIBW_BEFORE_BUILD: "conda update -y conda && conda install -y numpy scipy"
    CIBW_TEST_COMMAND: "python {project}/util/bee.py test -v"

  matrix:
    # For Python versions available on Appveyor, see 
    # http://www.appveyor.com/docs/installed-software#python
    # Use Anaconda as SciPy is a 
    # headache with Windows.
      # 3.6
    - PYTHON: "C:\\Miniconda36"
      # 3.6 64-bit
    - PYTHON: "C:\\Miniconda36-x64"
      # 3.5
    - PYTHON: "C:\\Miniconda35"
      # 3.5 64-bit
    - PYTHON: "C:\\Miniconda35-x64"
      # 3.4
    - PYTHON: "C:\\Miniconda3"
      # 3.4 64-bit
    - PYTHON: "C:\\Miniconda3-x64"
      # 2.7
    - PYTHON: "C:\\Miniconda"
      # 2.7 64-bit
    - PYTHON: "C:\\Miniconda-x64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "ECHO \"%APPVEYOR_SCHEDULED_BUILD%\""

install:
  # Prepend chosen Python to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "ECHO \"%APPVEYOR_SCHEDULED_BUILD%\""
  - >-
     %CMD_IN_ENV%
     python -c "import sys,platform,struct;
     print(sys.platform, platform.machine(), struct.calcsize('P') * 8, )"
  # Install the conda supplied packages; msvc_runtime needed for py34
  - "conda update -y conda"
  - "conda install -y pip wheel numpy scipy"

build_script:
  - pip install cibuildwheel==0.5.1
  - pip install .

test_script:
  - python util/bee.py test -v"
  - cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
