environment:
  global:
    PYTHON: "C:\\conda"
    CONDA_DEPENDENCIES: "numpy scipy"
    PIP_DEPENDENCIES: "six"
    CIBW_TEST_COMMAND: "python {project}/util/bee.py test -v"
 
  matrix:
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: 32

    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: 32
      SKIP_NOTAG: true

    - PYTHON_VERSION: "3.4"
      PYTHON_ARCH: 32
      SKIP_NOTAG: true

    - PYTHON_VERSION: "2.7"
      PYTHON_ARCH: 32

    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: 64
      SKIP_NOTAG: true

    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: 64
      SKIP_NOTAG: true

    - PYTHON_VERSION: "3.4"
      PYTHON_ARCH: 64
      SKIP_NOTAG: true

    - PYTHON_VERSION: "2.7"
      PYTHON_ARCH: 64
      SKIP_NOTAG: true

platform:
  - x86
  - x64

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "ECHO \"%APPVEYOR_SCHEDULED_BUILD%\""

install:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "ECHO \"%APPVEYOR_SCHEDULED_BUILD%\""

  # Check that we have the expected version and architecture for Python
  - python --version
  - >-
     %CMD_IN_ENV%
     python -c "import sys,platform,struct;
     print(sys.platform, platform.machine(), struct.calcsize('P') * 8, )"

build_script:
  - python setup.py build_ext --inplace
  - python util/bee.py test -v
  - pip install cibuildwheel==0.5.1
  - cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
